on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rsync Deployments Action
      uses: Burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: ./
        remote_path: ~/program/appel-bot-discord/
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USERNAME }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
